
// test

exports.test = async (req, res, next) => {
    try {
        
    } catch (error) {
        
    }
};